[package]
name = "day12ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ui = { path = "../../common/rs/ui", features = ["wasm-bindgen"]}

[dependencies.day12]
path = "../rs"
default-features = false
features = ["recursion"]

[dependencies.yew]
version = "0.21"
features = ["csr"]